// ─────────────────────────────────────────────────────────────────────────
// MOCK DATA — DEV/DEMO USE ONLY
// Import DEV_MODE from constants/config.ts and guard usage with it.
// In production, all data must come from Supabase directly.
// ─────────────────────────────────────────────────────────────────────────

import { TAX_RATES } from '@/constants/config';

export const MOCK_CONTRACTOR = {
  id: 'contractor-1',
  display_name: 'Marcus Webb',
  account_type: 'contractor',
  business_name: 'Webb & Sons Electrical',
  bio: 'Qualified electrician with 12 years experience. NICEIC approved. Specialising in domestic and commercial installations across Greater Manchester.',
  trades: ['Electrical', 'General Labour'],
  hourly_rate_from: 45,
  city: 'Manchester',
  postcode_area: 'M1',
  avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=200&h=200&fit=crop',
  tax_status: 'SELF_EMPLOYED' as 'CIS' | 'SELF_EMPLOYED',
  subscription: 'pro',
  rating: 4.8,
  review_count: 47,
  jobs_completed: 83,
};

export const MOCK_CUSTOMER = {
  id: 'customer-1',
  display_name: 'Sarah Thornton',
  account_type: 'customer',
  city: 'Manchester',
  postcode_area: 'M14',
  avatar: 'https://images.unsplash.com/photo-1494790108755-2616b612b829?w=200&h=200&fit=crop',
};

export const MOCK_PRIVATE_JOBS = [
  {
    id: 'job-1',
    contractor_id: 'contractor-1',
    title: 'Kitchen Full Rewire',
    customer: 'Dave & Linda Porter',
    description: 'Complete kitchen rewire including new consumer unit, 6 double sockets, 3 pendant lights and extractor fan circuit.',
    status: 'active',
    total: 1850,
    labour: 1200,
    materials: 542,
    vat: 108,
    materials_items: [
      { name: 'Consumer unit 18-way', qty: 1, price: 180 },
      { name: '2.5mm twin & earth cable (50m)', qty: 2, price: 65 },
      { name: 'Double socket outlets', qty: 6, price: 18 },
    ],
    receipts: [],
    invoiced_at: null,
    paid_at: null,
    created_at: '2026-06-01',
    source_job_post_id: null,
  },
  {
    id: 'job-2',
    contractor_id: 'contractor-1',
    title: 'EV Charger Installation',
    customer: 'Tom Ramirez',
    description: 'Supply and install 7kW home EV charger. OLEV grant applicable.',
    status: 'invoiced',
    total: 920,
    labour: 480,
    materials: 370,
    vat: 70,
    materials_items: [
      { name: 'Zappi 7kW charger', qty: 1, price: 320 },
      { name: '10mm cable (15m)', qty: 1, price: 50 },
    ],
    receipts: [],
    invoiced_at: '2026-06-05',
    paid_at: null,
    created_at: '2026-05-28',
    source_job_post_id: null,
  },
  {
    id: 'job-3',
    contractor_id: 'contractor-1',
    title: 'Office Lighting Upgrade',
    customer: 'Nexus Creative Ltd',
    description: 'Replace 24 fluorescent tubes with LED panels. New wiring, dimmer switches.',
    status: 'paid',
    total: 3200,
    labour: 1600,
    materials: 1300,
    vat: 300,
    materials_items: [],
    receipts: [],
    invoiced_at: '2026-05-20',
    paid_at: '2026-05-25',
    created_at: '2026-05-12',
    source_job_post_id: 'post-1',
  },
  {
    id: 'job-4',
    contractor_id: 'contractor-1',
    title: 'Bathroom Extractor Fan',
    customer: 'Priya Kapoor',
    description: 'Replace existing fan with new timer unit. Minor plaster patching.',
    status: 'draft',
    total: 280,
    labour: 200,
    materials: 67,
    vat: 13,
    materials_items: [],
    receipts: [],
    invoiced_at: null,
    paid_at: null,
    created_at: '2026-06-10',
    source_job_post_id: null,
  },
];

export const MOCK_JOB_POSTS = [
  {
    id: 'post-1',
    client_id: 'customer-1',
    client_name: 'Sarah Thornton',
    client_avatar: 'https://images.unsplash.com/photo-1494790108755-2616b612b829?w=100&h=100&fit=crop',
    title: 'Full bathroom refurbishment',
    description: 'Looking for an experienced plumber/tiler to fully refurbish my main bathroom. Strip out old suite, new bath, sink, toilet, full tile job. Approx 3x4m bathroom.',
    trade: 'Plumbing',
    status: 'open',
    budget: 4500,
    city: 'Manchester',
    postcode_area: 'M14',
    photo_url: 'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=600&h=400&fit=crop',
    ai_scope: 'Strip and remove existing bathroom suite (bath, basin, toilet). Install new freestanding bath, vanity unit, close-coupled WC. Tile floor and walls (approx 32m²). Fit new radiator and thermostatic bar shower.',
    ai_materials: ['Ceramic wall tiles (32m²)', 'Floor tiles (12m²)', 'Freestanding bath', 'Vanity basin unit', 'Close-coupled WC set', 'Shower bar valve', 'Tile adhesive x8 bags', 'Grout x4 bags'],
    applications: 3,
    created_at: '2026-06-08',
  },
  {
    id: 'post-2',
    client_id: 'customer-2',
    client_name: 'James Holbrook',
    client_avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop',
    title: 'Loft conversion electrical fit-out',
    description: 'New loft conversion needs full electrical fit-out. 8 sockets, 6 downlights, smoke detector, TV point. Consumer unit upgrade likely required.',
    trade: 'Electrical',
    status: 'open',
    budget: 2800,
    city: 'Salford',
    postcode_area: 'M6',
    photo_url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&h=400&fit=crop',
    ai_scope: null,
    ai_materials: null,
    applications: 1,
    created_at: '2026-06-09',
  },
  {
    id: 'post-3',
    client_id: 'customer-3',
    client_name: 'Fiona Blake',
    client_avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop',
    title: 'Garden decking and pergola',
    description: 'Want a composite deck (approx 25m²) with a hardwood pergola structure over half of it. Looking for a quality finish, not budget.',
    trade: 'Carpentry',
    status: 'open',
    budget: 6000,
    city: 'Didsbury',
    postcode_area: 'M20',
    photo_url: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=600&h=400&fit=crop',
    ai_scope: null,
    ai_materials: null,
    applications: 5,
    created_at: '2026-06-07',
  },
  {
    id: 'post-4',
    client_id: 'customer-4',
    client_name: 'Ahmed Malik',
    client_avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop',
    title: 'Interior repaint — 4-bed house',
    description: 'Full interior repaint of 4 bed semi. All walls and ceilings. Will supply paint. Need clean prep work, filling any cracks first.',
    trade: 'Painting',
    status: 'in_progress',
    budget: 2200,
    city: 'Stockport',
    postcode_area: 'SK2',
    photo_url: 'https://images.unsplash.com/photo-1562259929-b4e1fd3aef09?w=600&h=400&fit=crop',
    ai_scope: null,
    ai_materials: null,
    applications: 2,
    created_at: '2026-06-04',
  },
];

export const MOCK_CONTRACTORS_PUBLIC = [
  {
    id: 'contractor-1',
    display_name: 'Marcus Webb',
    business_name: 'Webb & Sons Electrical',
    trades: ['Electrical'],
    hourly_rate_from: 45,
    city: 'Manchester',
    postcode_area: 'M1',
    avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=200&h=200&fit=crop',
    rating: 4.8,
    review_count: 47,
    jobs_completed: 83,
    bio: 'NICEIC approved electrician. 12 years experience.',
    available: true,
  },
  {
    id: 'contractor-2',
    display_name: 'Jake Brennan',
    business_name: 'Brennan Plumbing & Heating',
    trades: ['Plumbing'],
    hourly_rate_from: 55,
    city: 'Salford',
    postcode_area: 'M6',
    avatar: 'https://images.unsplash.com/photo-1566753323558-f4e0952af115?w=200&h=200&fit=crop',
    rating: 4.6,
    review_count: 31,
    jobs_completed: 56,
    bio: 'Gas Safe registered. 15 years in plumbing and heating.',
    available: true,
  },
  {
    id: 'contractor-3',
    display_name: 'Chloe Marsh',
    business_name: 'Marsh Decorating',
    trades: ['Painting'],
    hourly_rate_from: 30,
    city: 'Didsbury',
    postcode_area: 'M20',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=200&h=200&fit=crop',
    rating: 4.9,
    review_count: 62,
    jobs_completed: 104,
    bio: 'Specialist in interior and exterior decoration. CSCS card holder.',
    available: false,
  },
];

export const MOCK_MANUAL_INCOME = [
  {
    id: 'inc-1',
    contractor_id: 'contractor-1',
    amount: 1200,
    date: '2026-05-15',
    customer_name: 'Private Client',
    category: 'Electrical',
    payment_status: 'paid',
    tax_rate: 30,
    tax_set_aside: 360,
    created_at: '2026-05-15',
    source: 'manual',
  },
  {
    id: 'inc-2',
    contractor_id: 'contractor-1',
    amount: 850,
    date: '2026-05-22',
    customer_name: 'Henderson Family',
    category: 'Electrical',
    payment_status: 'paid',
    tax_rate: 30,
    tax_set_aside: 255,
    created_at: '2026-05-22',
    source: 'manual',
  },
  {
    id: 'inc-3',
    contractor_id: 'contractor-1',
    amount: 440,
    date: '2026-06-03',
    customer_name: null,
    category: 'General Labour',
    payment_status: 'unpaid',
    tax_rate: 30,
    tax_set_aside: 132,
    created_at: '2026-06-03',
    source: 'manual',
  },
];

export const MOCK_PAI_INCOME = [
  {
    id: 'pai-inc-1',
    job_id: 'job-3',
    contractor_id: 'contractor-1',
    customer_id: 'customer-1',
    customer_name: 'Nexus Creative Ltd',
    amount: 3200,
    date_completed: '2026-05-25',
    tax_rate: 30,
    tax_set_aside: 960,
    net_payout: 2240,
    created_at: '2026-05-25',
    source: 'pai',
  },
];

export const MOCK_REVIEWS = [
  {
    id: 'rev-1',
    author_id: 'customer-1',
    author_name: 'Sarah T.',
    subject_id: 'contractor-1',
    rating: 5,
    comment: 'Marcus was brilliant — arrived on time, tidy work, explained everything clearly. Highly recommend.',
    created_at: '2026-05-26',
  },
  {
    id: 'rev-2',
    author_id: 'customer-2',
    author_name: 'James H.',
    rating: 5,
    comment: 'Second time using Webb & Sons. Always professional, fair pricing. Will use again.',
    created_at: '2026-04-14',
  },
  {
    id: 'rev-3',
    author_id: 'customer-3',
    author_name: 'Fiona B.',
    rating: 4,
    comment: 'Good work overall. Took slightly longer than quoted but kept us informed throughout.',
    created_at: '2026-03-08',
  },
];

export const MOCK_DISPUTES = [
  {
    id: 'dispute-1',
    job_post_id: 'post-2',
    job_title: 'Loft conversion electrical fit-out',
    contractor_name: 'Marcus Webb',
    customer_name: 'James Holbrook',
    amount: 2800,
    status: 'open',
    filed_by: 'customer',
    reason: 'Contractor marked job complete but smoke detector was not installed as agreed.',
    created_at: '2026-06-09',
  },
  {
    id: 'dispute-2',
    job_post_id: 'post-4',
    job_title: 'Interior repaint — 4-bed house',
    contractor_name: 'Chloe Marsh',
    customer_name: 'Ahmed Malik',
    amount: 2200,
    status: 'resolved',
    filed_by: 'contractor',
    reason: 'Customer refused to release payment after work was fully completed to spec.',
    resolution: 'Funds released to contractor after evidence reviewed.',
    created_at: '2026-06-05',
    resolved_at: '2026-06-08',
  },
];

export function calculateTaxSummary(manualIncome: typeof MOCK_MANUAL_INCOME, paiIncome: typeof MOCK_PAI_INCOME, taxRate: number) {
  const manualTotal = manualIncome.filter(i => i.payment_status === 'paid').reduce((s, i) => s + i.amount, 0);
  const paiTotal = paiIncome.reduce((s, i) => s + i.amount, 0);
  const totalEarnings = manualTotal + paiTotal;
  const totalSetAside = manualIncome.filter(i => i.payment_status === 'paid').reduce((s, i) => s + i.tax_set_aside, 0)
    + paiIncome.reduce((s, i) => s + i.tax_set_aside, 0);

  // Yearly projection based on current run rate (we're ~5 months into tax year April-April)
  const monthsElapsed = 2.5;
  const monthlyRate = totalEarnings / monthsElapsed;
  const yearlyProjection = monthlyRate * 12;
  const estimatedTax = yearlyProjection * (taxRate / 100);
  const monthlySetAside = estimatedTax / 12;

  return {
    totalSetAside,
    paiIncomeTotal: paiTotal,
    manualIncomeTotal: manualTotal,
    totalEarnings,
    yearlyProjection,
    estimatedTax,
    monthlySetAside,
  };
}
